accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [
    path('basic_signup/', views.basic_signup, name='basic_signup'),
    path('signup/', views.signup, name='signup'),
    path('kakao/disconnect/', views.kakao_disconnect, name='kakao_disconnect'),
    path('delete/', views.delete, name='delete'),
    path('basic_login/', views.basic_login, name='basic_login'),
    path('login/', views.login, name='login'),
    path('basic_logout/', views.basic_logout, name='basic_logout'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('set_default_profile_image/', views.set_default_profile_image, name='set_default_profile_image'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greatchoice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from reviews import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_redirect),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:category_type>/', views.category, name='category'),
    path('search/', views.search, name='search'),
    path('product_detail/<int:data_id>/', views.product_detail, name='product_detail'),
    path('create/<int:data_id>/', views.create, name='create'),
    path('review_delete/<int:review_pk>/', views.review_delete, name='review_delete'),
    path('review_update/<int:review_pk>/', views.review_update, name='review_update'),
    path('review_detail/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('review_like/<int:review_pk>/', views.review_like, name='review_like'),
    path('comment_create/<int:review_pk>/', views.comment_create, name='comment_create'),
    path('comment_like/<int:review_pk>/<int:comment_pk>/', views.comment_like, name='comment_like'),
    path('comment_delete/<int:review_pk>/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models
from django.conf import settings

class Product(models.Model):
    title = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    photo = models.CharField(max_length=255)
    data_id = models.IntegerField()


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    photo = models.CharField(max_length=255)
    review_product_id = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review_title = models.CharField(max_length=50)
    content = models.TextField()
    review_photo = models.ImageField(blank=True, null=True, upload_to='review_images/')
    score = models.IntegerField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

reviews/forms.py
from django import forms
from .models import Product, Review, Comment


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title','photo',)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('review_title','content','review_photo',)

    review_title = forms.CharField(
        label='제목',
        label_suffix='',
        widget=forms.TextInput(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5',
                'placeholder': '제목',
            }
        )
    )

    content = forms.CharField(
        label='내용',
        label_suffix='',
        widget=forms.Textarea(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5',
                'placeholder': '내용',
            }
        )
    )


    review_photo = forms.ImageField(
        label='이미지',
        label_suffix='',
        required = False,
        widget=forms.FileInput (
            attrs={
                'placeholder': '이미지',
            }
        )
    )

    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Product, Review, Comment
from .forms import ReviewForm, CommentForm
import requests
from bs4 import BeautifulSoup
from django.db.models import Avg
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect

# Create your views here.
def index_redirect(request):
    return redirect('reviews:index')


def index(request):
    ranking_url = 'https://search.musinsa.com/ranking/best?u_cat_cd='
    res = requests.get(ranking_url)
    soup = BeautifulSoup(res.text, 'html.parser')

    products_ranking = []
    for item in soup.select('.li_inner')[:15]:
        product = Product()
        product.data_id = item.select_one('a.img-block')['href'].split('?')[0].split('/')[-1]
        product.brand = item.select('.article_info > p > a')[0].text.strip()
        product.title = item.select('.article_info > p > a')[1].contents[-1].strip()
        product.photo = item.select('.lazyload')[0]['data-original']
        products_ranking.append(product)
    
    
    showcase_url = "https://www.musinsa.com/app/showcase/lists"
    headers = { "User-Agent": "Mozilla/5.0" }
    showcase_res = requests.get(showcase_url, headers=headers)
    showcase_soup = BeautifulSoup(showcase_res.text, "html.parser")

    showcase_data = []
    for item in showcase_soup.select('.n-card-list .n-card-img')[:3]:
        showcase_link = item.select_one('a')['href']
        showcase_img = item.select_one('img')['src']
        showcase_data.append({'link': showcase_link, 'image': showcase_img})
    
    
    Product.objects.all().delete()

    Product.objects.bulk_create(products_ranking)

    context = {
        'products_ranking': products_ranking,
        'showcase_data': showcase_data,
    }
    return render(request,'reviews/index.html', context)


def search(request):
    query = request.GET.get('query')

    search_url = f'https://www.musinsa.com/search/musinsa/goods?q={query}'
    res = requests.get(search_url)
    soup = BeautifulSoup(res.text, 'html.parser')
    
    products_search = []

    for item in soup.select('.li_inner'):
        product = Product()
        product.brand = item.select('.article_info > p > a')[0].text.strip()
        product.title = item.select('.article_info > p > a')[1].contents[-1].strip()
        product.photo = item.select('.lazyload')[0]['data-original']
        product.data_id = item.select_one('[data-bh-content-no]')['data-bh-content-no']
        products_search.append(product)

    Product.objects.all().delete()

    Product.objects.bulk_create(products_search)

    products = Product.objects.order_by('-pk')
    per_page = 12
    paginator = Paginator(products, per_page)
    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    context = {
        'products': page_obj,
        'products_search': products_search,
        'query': query,
    }
    return render(request,'reviews/search.html', context)


def category(request, category_type):
    if category_type == 'top':
        category_url = 'https://www.musinsa.com/categories/item/001'
        category_title = '상의'
    elif category_type == 'outerwear':
        category_url = 'https://www.musinsa.com/categories/item/002'
        category_title = '아우터'
    elif category_type == 'bottoms':
        category_url = 'https://www.musinsa.com/categories/item/003'
        category_title = '하의'
    elif category_type == 'shoes':
        category_url = 'https://www.musinsa.com/categories/item/005'
        category_title = '신발'

    res = requests.get(category_url)
    soup = BeautifulSoup(res.text, 'html.parser')
    
    products_category = []
    for item in soup.select('#goods_list .li_inner')[:36]:
        product = Product()
        product.data_id = item.select_one('a.img-block')['href'].split('?')[0].split('/')[-1]
        product.brand = item.select('.article_info > p > a')[0].text.strip()
        product.title = item.select('.article_info > p > a')[1].contents[-1].strip()
        product.photo = item.select('.lazyload')[0]['data-original']
        products_category.append(product)


    Product.objects.all().delete()

    Product.objects.bulk_create(products_category)

    products = Product.objects.order_by('-pk')
    per_page = 12
    paginator = Paginator(products, per_page)
    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    context = {
        'products': page_obj,
        'products_category': products_category,
        'category_title': category_title,
    }
    return render(request, 'reviews/category.html', context)


def product_detail(request, data_id):
    if Product.objects.filter(data_id=data_id).exists():
        product = Product.objects.get(data_id=data_id)
        product_exists = True
        selected_review = None
    else:
        selected_review = Review.objects.filter(review_product_id=data_id).first()
        product_exists = False
        product = None

    reviews = Review.objects.filter(review_product_id=data_id).order_by('-pk')
    review_count = len(reviews)
    page = request.GET.get('page', '1')
    paginator = Paginator(reviews, 5)
    page_obj = paginator.get_page(page)
    average_score = reviews.aggregate(Avg('score'))
    

    context = {
        'product_exists': product_exists,
        'product': product,
        'review': selected_review,
        'reviews': page_obj,
        'review_count': review_count,
        'average_score': average_score['score__avg'],
    }
    return render(request, 'reviews/detail.html', context)


@login_required
def create(request, data_id):
    if request.user.is_authenticated:
        if Product.objects.filter(data_id=data_id).exists():
            product = Product.objects.get(data_id=data_id)
            product_exists = True
            selected_review = None
        else:
            selected_review = Review.objects.filter(review_product_id=data_id).first()
            product_exists = False
            product = None

        if request.method == 'POST':
            review_form = ReviewForm(request.POST, request.FILES)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                if Product.objects.filter(data_id=data_id).exists():
                    review.title = product.title
                    review.brand = product.brand
                    review.photo = product.photo
                    review.review_product_id = product.data_id
                else:
                    review.title = selected_review.title
                    review.brand = selected_review.brand
                    review.photo = selected_review.photo
                    review.review_product_id = selected_review.review_product_id

                review.score = int(request.POST['score'])
                review.user = request.user
                review.save()
                return redirect('reviews:product_detail', data_id)
        else:
            review_form = ReviewForm()
    else:
        return redirect('accounts:basic_login')
    context = {
        'review_form': review_form,
        'product': product,
        'review': selected_review,
        'product_exists': product_exists,
    }
    return render(request, 'reviews/create.html', context)


@login_required
def review_delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user :
        review.delete()
    return redirect('reviews:index')


@login_required
def review_update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, request.FILES, instance=review)
            if form.is_valid():
                form.save()
                review.score = int(request.POST['score'])
                return redirect('reviews:review_detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('reviews:review_detail', review.pk)
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'reviews/review_update.html', context)


@login_required
def review_like(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        review_is_liked = False
    else:
        review.like_users.add(request.user)
        review_is_liked = True
    context = {
        'review_is_liked': review_is_liked,
        'review_likes_count': review.like_users.count(),
    }
    return JsonResponse(context)


def review_detail(request, review_pk):
    comments = Comment.objects.filter(review=review_pk).order_by('-pk')
    review = Review.objects.get(pk=review_pk)
    context = {
        'review': review,
        'form': CommentForm,
        'comments': comments,
    }
    return render(request, 'reviews/review_detail.html', context)


@login_required
def comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
            return redirect('reviews:review_detail', review.pk)
        
        else :
            messages.warning(request, "댓글은 빈칸으로 제출하실 수 없습니다.")
            return redirect('reviews:review_detail', review.pk)


@login_required
def comment_like(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
        comment_is_liked = False
    else:

reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<!-- CSS 파일 로드 -->
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block body %}

<div class="create_container">
    <div class="create_card">
        {% if product_exists %}
            <img class="create_img" src="{{ product.photo }}" alt="이미지 없음">
            <div class="create_text">
                <strong><p class="create_brand">{{ product.brand }}</p></strong>
                <p class="create_title">{{ product.title }}</p>
            </div>
        {% else %}
            <img class="create_img" src="{{ review.photo }}" alt="이미지 없음">
            <div class="create_text">
                <strong><p class="create_brand">{{ review.brand }}</p></strong>
                <p class="create_title">{{ review.title }}</p>
            </div>
        {% endif %}
    </div>
    <div class="create_form_container">
        {% if product_exists %}
            <form action="{% url 'reviews:create' product.data_id %}" method="POST" enctype="multipart/form-data">
        {% else %}
            <form action="{% url 'reviews:create' review.review_product_id %}" method="POST" enctype="multipart/form-data">
        {% endif %}
            {% csrf_token %}
            <div class="rating review_rating">
                <div id="rating-stars"></div>
                <input type="hidden" id="score-input" name="score" value="0">
            </div>
            {% for field in review_form %}
                <p class="content_form">{{ field }}</p>
            {% endfor %}
            <div class="review_sumbit">
                <input type="submit" value='리뷰쓰기'>
            </div>
        </form>
    </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
<script>
    $(document).ready(function() {
        $("#rating-stars").rateYo({
            starWidth: "25px",
            spacing: "10px",
            fullStar: true,
            precision: 1,
            onSet: function(rating, rateYoInstance) {
                $("#score-input").val(rating.toFixed(0));
            }
        });
    });    
</script>

{% endblock body %}

reviews/templates/reviews/review_detail.html
{% extends 'base.html' %}
{% block body %}
{% load custom_filters %}
{% load static %}
<div class="flex justify-center p-10 ">
  <div class="w-2/3">
    <!-- 상단(사용자 이름, 프로필 사진, 리뷰 작성일) -->
    <div class="flex justify-between items-center	space-x-4">
      <div class="flex items-center">
        <img class="w-10 h-10 rounded-full" src="{{ review.user.profile_image.url }}" alt="">
        <div class="ml-2">
          <p class="font-semibold">
            <a href="{% url 'accounts:profile' review.user.username %}">{{ review.user }}</a>
          </p>
          <div class="flex items-center">
            {% for i in 5|star_range %}
              {% if review.score > i %}
                <i class="fa-solid fa-star" style="color: #fad900;"></i>
              {% else %}
                <i class="fa-solid fa-star" style="color: #808080;"></i>
              {% endif %}
            {% endfor %}
            <span class="ml-1 text-base font-semibold">{{ review.score }}</span>
          </div>
        </div>
      </div>
      <div class="font-base">
        <span class="text-sm text-gray-500">{{ review.created_at|date:"Y-m-d"}}</span>
      </div>
    </div>
    <div class="flex justify-end">
      {% if request.user == review.user %}
        <!-- 리뷰 수정 기능 -->
        <a href="{% url 'reviews:review_update' review.pk %}" class="mr-3">
          <i class="fa-regular fa-pen-to-square"></i>
        </a>
        <!-- 리뷰 삭제 기능 -->
        <form action="{% url 'reviews:review_delete' review.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit">
            <i class="fa-sharp fa-regular fa-trash-can"></i>
          </button>
        </form>
      {% endif %}
    </div>
    <!-- 상품 정보 -->
    <div class="mb-3 w-1/3">
      <a href="{% url 'reviews:product_detail' review.review_product_id %}" class="flex">
        <img src="{{ review.photo }}" alt="상품 이미지" class="rounded-lg w-16 mr-2">
      <p class="text-sm self-center">{{ review.title }}</p>
      </a>
    </div>
    
    <!-- 리뷰 내용(평점, 후기, 사진)-->
    <div class="mt-3 mb-10">
      <h3 class="text-xl font-semibold text-gray-900">{{ review.review_title }}</h3>
      <div class="text=xl">{{ review.content }}</div>
      <!-- 사진 클릭시 확대 -->
      <!-- Modal toggle -->
      {% if review.review_photo %}
        <button data-modal-target="defaultModal" data-modal-toggle="defaultModal" class="block" type="button">
          <img src="{{ review.review_photo.url }}" alt="리뷰 사진" class="w-56 h-56 rounded-lg mt-2">
        </button>
        <!-- Main modal -->
        <div id="defaultModal" tabindex="-1" aria-hidden="true" class="fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full">
          <div class="relative w-full max-w-2xl max-h-full">
            <!-- Modal content -->
            <div class="relative bg-white rounded-lg shadow">
              <!-- Modal header -->
              <div class="flex items-end p-4 rounded-t">
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-hide="defaultModal">
                  <i class="fa-solid fa-x"></i>
                  <span class="sr-only">Close modal</span>
                </button>
              </div>
              <!-- Modal body -->
              <div class="p-6">
                <img src="{{ review.review_photo.url }}" alt="리뷰 사진" class="w-full h-auto rounded-lg">
              </div>
            </div>
          </div>
        </div>
      {% endif %}

      <!-- 리뷰 좋아요 기능 -->
      <div class="flex items-center justify-end mr-3">
        {% if request.user != review.user %}
          <form id="review-like-form" data-review-id="{{ review.pk }}">
            {% csrf_token %}
            {% if request.user in review.like_users.all %}
              <button type="submit">
                <i id="heart_icon" class="fa-heart fa-solid" style="color: #ff0000;"></i>
              </button>
            {% else %}
              <button type="submit">
                <i id="heart_icon" class="fa-heart fa-regular" style="color: #ff0000;"></i>
              </button>
            {% endif %}
          </form>
        {% else %}
          {% if review.like_users.count > 0 %}
            <i id="heart_icon" class="fa-heart fa-solid" style="color: #ff0000;"></i>
          {% else %}
            <i id="heart_icon" class="fa-heart fa-regular" style="color: #ff0000;"></i>
          {% endif %}
        {% endif %}
        <sapn id="review_likes_count" class="ml-1 text-base text-gray-500">{{ review.like_users.count }}</sapn>
      </div>
    </div>

    <!-- 댓글창 -->
    {% if request.user.is_authenticated %}
      <form action="{% url 'reviews:comment_create' review.pk %}" method="POST">
        {% csrf_token %}
        <div class="grid grid-cols-7 mt-3">
          <div class="col-span-6">
            <textarea name="content" rows="4" class="block p-2.5 w-full text-base text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500" placeholder="댓글을 입력하세요."></textarea>
          </div>
          <div class="col">
            <button type="submit" class="text-white bg-gray-800 hover:bg-gray-900 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-base px-5 py-2.5 ml-2 w-full h-full focus:outline-none">댓글 작성</button>
          </div>
        </div>
      </form>
    {% else %}
      <div class="grid grid-cols-7 mt-3">
        <div class="col-span-6">
          <textarea name="content" rows="4" class="block p-2.5 w-full text-base text-gray-900 bg-gray-100 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500" placeholder="로그인이 필요합니다." disabled></textarea>
        </div>
        <div class="col">
          <button type="submit" class="text-white bg-gray-500 font-medium rounded-lg text-base px-5 py-2.5 ml-2 w-full h-full" disabled>댓글 작성</button>
        </div>
      </div>
    {% endif %}
    

    <!-- 댓글 목록 -->
    <h1 class="my-5 text-xl">댓글({{ comments.count }})</h1>
    {% if comments %}
      {% for comment in comments %}
        <div class="grid grid-cols-8 mt-3">
          <div class="col-span-1 flex items-center">
            <img class="w-10 h-10 rounded-full" src="{{ comment.user.profile_image.url }}" alt="">
            <p class="font-semibold ml-2">
              <a href="{% url 'accounts:profile' comment.user.username %}">{{ comment.user }}</a>
            </p>
          </div>
          <div class="col-span-6 text-base flex items-center">
            {{ comment.content }}
          </div>
          <div class="col-span-1 text-base flex items-center justify-end">
            <!-- 댓글 삭제 기능 -->
            {% if request.user == comment.user %}
            <form action="{% url 'reviews:comment_delete' review.pk comment.pk %}" method="POST" class="mr-2">
              {% csrf_token %}
              <button type="submit">
                <i class="fa-sharp fa-regular fa-trash-can"></i>
              </button>
            </form>
            {% endif %}
            <!-- 댓글 좋아요 기능 -->
            {% if request.user != comment.user %}
              <form id="review-comment-like-form-{{ comment.pk }}" data-review-id="{{ review.pk }}" data-comment-id="{{ comment.pk }}">
                {% csrf_token %}
                {% if request.user in comment.like_users.all %}
                  <button type="submit">
                    <i id="comment_heart_icon" class="fa-heart fa-solid" style="color: #ff0000;"></i>
                  </button>
                {% else %}
                  <button type="submit">
                    <i id="comment_heart_icon" class="fa-heart fa-regular" style="color: #ff0000;"></i>
                  </button>
                {% endif %}
              </form>
            {% else %}
              {% if comment.like_users.count > 0 %}
                <i id="heart_icon" class="fa-heart fa-solid" style="color: #ff0000;"></i>
              {% else %}
                <i id="heart_icon" class="fa-heart fa-regular" style="color: #ff0000;"></i>
              {% endif %}
            {% endif %}
            <span id="review_comment_likes_count" class="ml-1 text-base text-gray-500">{{ comment.like_users.count }}</span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div>댓글이 없습니다.</div>
    {% endif %}
  </div>
</div>
{% endblock body %}

{% block js %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#review-like-form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const reviewId = event.target.dataset.reviewId
      axios({
        method: 'post',
        url: `/reviews/review_like/${reviewId}/`,
        headers: {'X-CSRFToken': csrftoken,}
      })
        .then((response) => {
          const reviewIsLiked = response.data.review_is_liked
          const likeBtn = document.querySelector('#heart_icon')

          if (reviewIsLiked === true) {
            likeBtn.classList.add('fa-solid');
            likeBtn.classList.remove('fa-regular');
          } else {
            likeBtn.classList.add('fa-regular');
            likeBtn.classList.remove('fa-solid');
          }
          const reviewLikeCountTag = document.querySelector('#review_likes_count')
          const reviewLikeData = response.data.review_likes_count
          reviewLikeCountTag.textContent = reviewLikeData
        })
    })


    const commentLikeForms = document.querySelectorAll('[id^="review-comment-like-form-"]');
    const r_csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    commentLikeForms.forEach(function(commentLikeForm) {
      commentLikeForm.addEventListener('submit', function(event) {
        event.preventDefault();
        const reviewId = event.target.dataset.reviewId;
        const commentId = event.target.dataset.commentId;
        axios({
          method: 'POST',
          url: `/reviews/comment_like/${reviewId}/${commentId}/`,
          headers: { 'X-CSRFToken': r_csrftoken }
        })
          .then((response) => {
            const commentIsLiked = response.data.comment_is_liked;
            const commentLikeBtn = event.target.querySelector('#comment_heart_icon');

            if (commentIsLiked === true) {
              commentLikeBtn.classList.add('fa-solid');
              commentLikeBtn.classList.remove('fa-regular');
            } else {
              commentLikeBtn.classList.add('fa-regular');
              commentLikeBtn.classList.remove('fa-solid');
            }
            
            const reviewCommentLikeCountTag = event.target.nextElementSibling;
            const reviewCommentLikeData = response.data.review_comment_likes_count;
            reviewCommentLikeCountTag.textContent = reviewCommentLikeData;
          });
      });
    });
  </script>
{% endblock js %}

reviews/templates/reviews/review_update.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<!-- CSS 파일 로드 -->
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock %}

{% block body %}

<div class="create_container">
  <div class="create_card">
    <img class="create_img" src="{{ review.photo }}" alt="이미지 없음">
    <div class="create_text">
      <strong><p class="create_brand">{{ review.brand }}</p></strong>
      <p class="create_title">{{ review.title }}</p>
    </div>
  </div>
  <div class="create_form_container">
    <form action="{% url 'reviews:review_update' review.pk %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="rating review_rating">
        <div id="rating-stars"></div>
        <input type="hidden" id="score-input" name="score" value="0">
      </div>
      {% for field in form %}
        <p class="content_form">{{ field }}</p>
      {% endfor %}
      <div class="review_sumbit">
        <input type="submit" value='리뷰 수정'>
      </div>
    </form>
  </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
<script>
    $(document).ready(function() {
        $("#rating-stars").rateYo({
            starWidth: "25px",
            spacing: "10px",
            rating: {{ review.score }},
            fullStar: true,
            precision: 1,
            onSet: function(rating, rateYoInstance) {
                $("#score-input").val(rating.toFixed(0));
            }
        });
    });    
</script>

{% endblock body %}