accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [
    path('basic_signup/', views.basic_signup, name='basic_signup'),
    path('signup/', views.signup, name='signup'),
    path('kakao/disconnect/', views.kakao_disconnect, name='kakao_disconnect'),
    path('delete/', views.delete, name='delete'),
    path('basic_login/', views.basic_login, name='basic_login'),
    path('login/', views.login, name='login'),
    path('basic_logout/', views.basic_logout, name='basic_logout'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('set_default_profile_image/', views.set_default_profile_image, name='set_default_profile_image'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greatchoice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from reviews import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_redirect),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:category_type>/', views.category, name='category'),
    path('search/', views.search, name='search'),
    path('product_detail/<int:data_id>/', views.product_detail, name='product_detail'),
    path('create/<int:data_id>/', views.create, name='create'),
    path('review_delete/<int:review_pk>/', views.review_delete, name='review_delete'),
    path('review_update/<int:review_pk>/', views.review_update, name='review_update'),
    path('review_detail/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('review_like/<int:review_pk>/', views.review_like, name='review_like'),
    path('comment_create/<int:review_pk>/', views.comment_create, name='comment_create'),
    path('comment_like/<int:review_pk>/<int:comment_pk>/', views.comment_like, name='comment_like'),
    path('comment_delete/<int:review_pk>/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    username = models.CharField(max_length=150, unique=True)
    password = models.CharField(max_length=128)  # 비밀번호 필드
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    profile_image = models.ImageField(blank=True, null=True, upload_to='profile_images')

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm , UserChangeForm
from django.contrib.auth import get_user_model
from django import forms


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        required=True,
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'id': "floating_username",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
        })
    )

    password = forms.CharField(
        required=True,
        label='비밀번호',
        widget=forms.TextInput(
            attrs={
                'type': 'password',
                'id': "floating_password",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
        })
    )


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'id': "floating_username",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
        })
    )
    password1 = forms.CharField(
        required=True,
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'id': "floating_password",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
        })
    )
    password2 = forms.CharField(
        required=True,
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'id': "floating_repeat_password",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
        })
    )
    profile_image = forms.ImageField(
        required=False,
        label='프로필 이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'id': "floating_profile_image",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
            }
        )
    )


    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('username', 'password1', 'password2','profile_image',)


class CustomUserChangeForm(UserChangeForm):
    username = forms.CharField(
        required=True,
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'id': "floating_username",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
        })
    )
    profile_image = forms.ImageField(
        required=False,
        label='프로필 이미지',
        widget=forms.ClearableFileInput(
            attrs={
                'id': "floating_profile_image",
                'class': 'block w-full py-2.5 px-0 text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 focus:outline-none focus:border-blue-600 peer',
                'placeholder': " "
            }
        )
    )



    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ('username', 'profile_image',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from .forms import CustomAuthenticationForm, CustomUserCreationForm , CustomUserChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from allauth.socialaccount.models import SocialAccount
from django.core.files import File
import urllib.request
from django.core.paginator import Paginator
from django.http import JsonResponse


def kakao_disconnect(request):
    if request.user.is_authenticated:
        # 사용자의 카카오 소셜 계정 연결 끊기
        SocialAccount.objects.filter(user=request.user, provider='kakao').delete() 
    # 계정 삭제 후 리다이렉트할 URL
        redirect_url = 'reviews:index'
    return redirect('reviews:index')


def basic_login(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')
    
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('reviews:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')
    
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('reviews:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def basic_logout(request):
    auth_logout(request)
    return redirect('reviews:index')


@login_required
def logout(request):
    auth_logout(request)
    return redirect('reviews:index')


def basic_signup(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST,request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            if not user.profile_image:
                image_url = 'https://picsum.photos/200'
                response = urllib.request.urlopen(image_url)
                user.profile_image.save('default_image.jpg', File(response), save=True)
            user.save()
            auth_login(request, user)
            return redirect('reviews:index') 
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('reviews:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('reviews:index') 
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def update(request):
    User = get_user_model()
    person = User.objects.get(username=request.user.username)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('accounts:profile', user.username) 
    else:
        form = CustomUserChangeForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('reviews:index')


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    
    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
            is_followed = False
        else:
            person.followers.add(request.user)
            is_followed = True
        context = {
            'is_followed': is_followed,
            'followings_count': person.followings.count(),
            'followers_count': person.followers.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    if not person.profile_image:
        image_url = 'https://picsum.photos/200'  # 기본 이미지 URL
        response = urllib.request.urlopen(image_url)
        default_image = File(response)
        person.profile_image.save('default_image.jpg', default_image, save=True)
        person.save()
    is_kakao_connected = SocialAccount.objects.filter(user=request.user, provider='kakao').exists()
    reviews = person.review_set.all().order_by('-created_at')
    like_reviews = person.like_reviews.all().order_by('-created_at')
    active_tab = request.GET.get("tab")  # 선택된 탭을 가져옴

    if active_tab == "reviews":
        content = reviews
    elif active_tab == "like_reviews":  
        content = like_reviews
    else:
        content = reviews

    per_page = 4
    paginator = Paginator(content, per_page)
    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    context = {
        'is_kakao_connected': is_kakao_connected,
        'person': person,
        'reviews':reviews,
        'like_reviews': like_reviews,
        'page_obj': page_obj,
        'active_tab': active_tab,
        'username': username,
    }
    return render(request, 'accounts/profile.html', context)


def set_default_profile_image(request):
    user = request.user
    # 이미지 URL에서 이미지를 가져와서 프로필 이미지로 설정
    image_url = 'https://picsum.photos/200'
    response = urllib.request.urlopen(image_url)
    user.profile_image.save('default_image.jpg', File(response), save=True)

    return redirect('accounts:profile', request.user.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block body %}
{% load static %}

  <div class="mt-10">
    <h1 class="text-center text-3xl mb-8">로그인</h1>
    <form action="{% url 'accounts:basic_login' %}" method="POST" class="flex flex-col items-center">
      {% csrf_token %}
      <div class="relative mb-10 w-1/4">
        {{ form.username }}
        <label for="floating_username" class="absolute text-gray-500 duration-300 transform -translate-y-9 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-9">아이디</label>
      </div>
      <div class="relative mb-10 w-1/4">
        {{ form.password }}
        <label for="floating_password" class="absolute text-gray-500 duration-300 transform -translate-y-9 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-9">비밀번호</label>
      </div>
      <div class="mb-3 w-1/4">
        <button type="submit" class="w-full text-white bg-gray-800 hover:bg-gray-900 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg px-5 py-2.5 text-center">로그인</button>
      </div>
    </form>
    <div class="flex flex-col items-center">
      <a href="{% provider_login_url 'kakao' %}" class="w-1/4 mb-10 flex justify-center rounded-lg" style="background-color:#FEE500">
        <img src="{% static 'img/kakao_login_button.png' %}" alt="카카오 로그인 이미지">
      </a>
    </div>
    <div class="flex flex-col items-center">
      <a href="{% url 'reviews:index' %}" class="flex flex-row w-1/4">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="block w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3"></svg>
          <span class="mx-3">돌아가기</span>
      </a>
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/pagination.html
{% if page_obj.has_previous or page_obj.has_next %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?{{ page_param }}={{ page_obj.previous_page_number }}" aria-label="이전">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
        {% endif %}

        {% for page in page_obj.paginator.page_range %}
            {% if page_obj.number == page %}
                <li class="page-item active">
                    <span class="page-link">{{ page }}</span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{{ page_param }}={{ page }}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?{{ page_param }}={{ page_obj.next_page_number }}" aria-label="다음">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
        {% endif %}
    </ul>
{% endif %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block body %}
  <div class="mt-10">
    <h1 class="text-center text-3xl mb-8">회원가입</h1>
    <form action="{% url 'accounts:basic_signup' %}" method="POST" class="flex flex-col items-center" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="relative mb-10 w-1/4">
        {{ form.username }}
        <label for="floating_username" class="absolute text-gray-500 duration-300 transform -translate-y-9 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-9">아이디</label>
      </div>
      <div class="relative mb-10 w-1/4">
        {{ form.password1 }}
        <label for="floating_password" class="absolute text-gray-500 duration-300 transform -translate-y-9 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-9">비밀번호</label>
      </div>
      <div class="relative mb-10 w-1/4">
        {{ form.password2 }}
        <label for="floating_repeat_password" class="absolute text-gray-500 duration-300 transform -translate-y-9 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-9">비밀번호 확인</label>
      </div>
      <div class="relative mb-10 w-1/4">
        {{ form.profile_image }}
      </div>
      <div class="w-1/4 mb-10">
        <button type="submit" class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5 text-center">회원가입</button>
      </div>
      
    </form>
    <div class="flex flex-col items-center">
      <a href="{% url 'reviews:index' %}" class="flex flex-row w-1/4">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="block w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 15L3 9m0 0l6-6M3 9h12a6 6 0 010 12h-3"></svg>
          <span class="mx-3">돌아가기</span>
      </a>
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="flex justify-center">
  <div class="card m-5" style="width:70%;">
  <div>
    <img src="{{ user.profile_image.url }}" class="w-24 h-24 m-3 mb-3 rounded-full shadow-lg" alt=''>
    <p class="mb-2 ml-5 text-blue-500" style="font-size: 24px;">나의 정보</p>
    <p class="mb-2 ml-5" >고객께서 가입하신 유신사 회원 정보입니다.</p>
  </div>
    <div class="card-body">
        <form class="flex flex-col items-left" action="{% url 'accounts:update' %} " method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="relative mb-10 w-1/4 flex items-center mb-2">
          <p class="col-3">아이디 : </p> {{ user.username }}  
          <div class="ml-3">
            {{ form.username }}
          </div>
          <label for="floating_username" class="absolute text-gray-500 duration-300 transform -translate-y-9 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-9">아이디</label>
        </div>
        <div class="relative mb-10 w-2/4 flex items-center mb-2">
          <p class="col-4">프로필 이미지 업로드 : </p>
          {{ form.profile_image }}
        </div>  
        <div class="w-1/4 self-end text-right">
          <button type='submit' class="text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg px-5 py-2.5">수정</button>
        </div>
        </form>
    </div>
  </div>
</div>
{% endblock body %}