accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'accounts'

urlpatterns = [
    path('basic_signup/', views.basic_signup, name='basic_signup'),
    path('signup/', views.signup, name='signup'),
    path('kakao/disconnect/', views.kakao_disconnect, name='kakao_disconnect'),
    path('delete/', views.delete, name='delete'),
    path('basic_login/', views.basic_login, name='basic_login'),
    path('login/', views.login, name='login'),
    path('basic_logout/', views.basic_logout, name='basic_logout'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('set_default_profile_image/', views.set_default_profile_image, name='set_default_profile_image'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greatchoice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from reviews import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_redirect),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<str:category_type>/', views.category, name='category'),
    path('search/', views.search, name='search'),
    path('product_detail/<int:data_id>/', views.product_detail, name='product_detail'),
    path('create/<int:data_id>/', views.create, name='create'),
    path('review_delete/<int:review_pk>/', views.review_delete, name='review_delete'),
    path('review_update/<int:review_pk>/', views.review_update, name='review_update'),
    path('review_detail/<int:review_pk>/', views.review_detail, name='review_detail'),
    path('review_like/<int:review_pk>/', views.review_like, name='review_like'),
    path('comment_create/<int:review_pk>/', views.comment_create, name='comment_create'),
    path('comment_like/<int:review_pk>/<int:comment_pk>/', views.comment_like, name='comment_like'),
    path('comment_delete/<int:review_pk>/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
from django.db import models
from django.conf import settings

class Product(models.Model):
    title = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    photo = models.CharField(max_length=255)
    data_id = models.IntegerField()


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    photo = models.CharField(max_length=255)
    review_product_id = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review_title = models.CharField(max_length=50)
    content = models.TextField()
    review_photo = models.ImageField(blank=True, null=True, upload_to='review_images/')
    score = models.IntegerField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')

reviews/forms.py
from django import forms
from .models import Product, Review, Comment


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('title','photo',)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('review_title','content','review_photo',)

    review_title = forms.CharField(
        label='제목',
        label_suffix='',
        widget=forms.TextInput(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5',
                'placeholder': '제목',
            }
        )
    )

    content = forms.CharField(
        label='내용',
        label_suffix='',
        widget=forms.Textarea(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5',
                'placeholder': '내용',
            }
        )
    )


    review_photo = forms.ImageField(
        label='이미지',
        label_suffix='',
        required = False,
        widget=forms.FileInput (
            attrs={
                'placeholder': '이미지',
            }
        )
    )

    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Product, Review, Comment
from .forms import ReviewForm, CommentForm
import requests
from bs4 import BeautifulSoup
from django.db.models import Avg
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect

# Create your views here.
def index_redirect(request):
    return redirect('reviews:index')


def index(request):
    ranking_url = 'https://search.musinsa.com/ranking/best?u_cat_cd='
    res = requests.get(ranking_url)
    soup = BeautifulSoup(res.text, 'html.parser')

    products_ranking = []
    for item in soup.select('.li_inner')[:15]:
        product = Product()
        product.data_id = item.select_one('a.img-block')['href'].split('?')[0].split('/')[-1]
        product.brand = item.select('.article_info > p > a')[0].text.strip()
        product.title = item.select('.article_info > p > a')[1].contents[-1].strip()
        product.photo = item.select('.lazyload')[0]['data-original']
        products_ranking.append(product)
    
    
    showcase_url = "https://www.musinsa.com/app/showcase/lists"
    headers = { "User-Agent": "Mozilla/5.0" }
    showcase_res = requests.get(showcase_url, headers=headers)
    showcase_soup = BeautifulSoup(showcase_res.text, "html.parser")

    showcase_data = []
    for item in showcase_soup.select('.n-card-list .n-card-img')[:3]:
        showcase_link = item.select_one('a')['href']
        showcase_img = item.select_one('img')['src']
        showcase_data.append({'link': showcase_link, 'image': showcase_img})
    
    
    Product.objects.all().delete()

    Product.objects.bulk_create(products_ranking)

    context = {
        'products_ranking': products_ranking,
        'showcase_data': showcase_data,
    }
    return render(request,'reviews/index.html', context)


def search(request):
    query = request.GET.get('query')

    search_url = f'https://www.musinsa.com/search/musinsa/goods?q={query}'
    res = requests.get(search_url)
    soup = BeautifulSoup(res.text, 'html.parser')
    
    products_search = []

    for item in soup.select('.li_inner'):
        product = Product()
        product.brand = item.select('.article_info > p > a')[0].text.strip()
        product.title = item.select('.article_info > p > a')[1].contents[-1].strip()
        product.photo = item.select('.lazyload')[0]['data-original']
        product.data_id = item.select_one('[data-bh-content-no]')['data-bh-content-no']
        products_search.append(product)

    Product.objects.all().delete()

    Product.objects.bulk_create(products_search)

    products = Product.objects.order_by('-pk')
    per_page = 12
    paginator = Paginator(products, per_page)
    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    context = {
        'products': page_obj,
        'products_search': products_search,
        'query': query,
    }
    return render(request,'reviews/search.html', context)


def category(request, category_type):
    if category_type == 'top':
        category_url = 'https://www.musinsa.com/categories/item/001'
        category_title = '상의'
    elif category_type == 'outerwear':
        category_url = 'https://www.musinsa.com/categories/item/002'
        category_title = '아우터'
    elif category_type == 'bottoms':
        category_url = 'https://www.musinsa.com/categories/item/003'
        category_title = '하의'
    elif category_type == 'shoes':
        category_url = 'https://www.musinsa.com/categories/item/005'
        category_title = '신발'

    res = requests.get(category_url)
    soup = BeautifulSoup(res.text, 'html.parser')
    
    products_category = []
    for item in soup.select('#goods_list .li_inner')[:36]:
        product = Product()
        product.data_id = item.select_one('a.img-block')['href'].split('?')[0].split('/')[-1]
        product.brand = item.select('.article_info > p > a')[0].text.strip()
        product.title = item.select('.article_info > p > a')[1].contents[-1].strip()
        product.photo = item.select('.lazyload')[0]['data-original']
        products_category.append(product)


    Product.objects.all().delete()

    Product.objects.bulk_create(products_category)

    products = Product.objects.order_by('-pk')
    per_page = 12
    paginator = Paginator(products, per_page)
    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    context = {
        'products': page_obj,
        'products_category': products_category,
        'category_title': category_title,
    }
    return render(request, 'reviews/category.html', context)


def product_detail(request, data_id):
    if Product.objects.filter(data_id=data_id).exists():
        product = Product.objects.get(data_id=data_id)
        product_exists = True
        selected_review = None
    else:
        selected_review = Review.objects.filter(review_product_id=data_id).first()
        product_exists = False
        product = None

    reviews = Review.objects.filter(review_product_id=data_id).order_by('-pk')
    review_count = len(reviews)
    page = request.GET.get('page', '1')
    paginator = Paginator(reviews, 5)
    page_obj = paginator.get_page(page)
    average_score = reviews.aggregate(Avg('score'))
    

    context = {
        'product_exists': product_exists,
        'product': product,
        'review': selected_review,
        'reviews': page_obj,
        'review_count': review_count,
        'average_score': average_score['score__avg'],
    }
    return render(request, 'reviews/detail.html', context)


@login_required
def create(request, data_id):
    if request.user.is_authenticated:
        if Product.objects.filter(data_id=data_id).exists():
            product = Product.objects.get(data_id=data_id)
            product_exists = True
            selected_review = None
        else:
            selected_review = Review.objects.filter(review_product_id=data_id).first()
            product_exists = False
            product = None

        if request.method == 'POST':
            review_form = ReviewForm(request.POST, request.FILES)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                if Product.objects.filter(data_id=data_id).exists():
                    review.title = product.title
                    review.brand = product.brand
                    review.photo = product.photo
                    review.review_product_id = product.data_id
                else:
                    review.title = selected_review.title
                    review.brand = selected_review.brand
                    review.photo = selected_review.photo
                    review.review_product_id = selected_review.review_product_id

                review.score = int(request.POST['score'])
                review.user = request.user
                review.save()
                return redirect('reviews:product_detail', data_id)
        else:
            review_form = ReviewForm()
    else:
        return redirect('accounts:basic_login')
    context = {
        'review_form': review_form,
        'product': product,
        'review': selected_review,
        'product_exists': product_exists,
    }
    return render(request, 'reviews/create.html', context)


@login_required
def review_delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user :
        review.delete()
    return redirect('reviews:index')


@login_required
def review_update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, request.FILES, instance=review)
            if form.is_valid():
                form.save()
                review.score = int(request.POST['score'])
                return redirect('reviews:review_detail', review.pk)
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('reviews:review_detail', review.pk)
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'reviews/review_update.html', context)


@login_required
def review_like(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user in review.like_users.all():
        review.like_users.remove(request.user)
        review_is_liked = False
    else:
        review.like_users.add(request.user)
        review_is_liked = True
    context = {
        'review_is_liked': review_is_liked,
        'review_likes_count': review.like_users.count(),
    }
    return JsonResponse(context)


def review_detail(request, review_pk):
    comments = Comment.objects.filter(review=review_pk).order_by('-pk')
    review = Review.objects.get(pk=review_pk)
    context = {
        'review': review,
        'form': CommentForm,
        'comments': comments,
    }
    return render(request, 'reviews/review_detail.html', context)


@login_required
def comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.review = review
            comment.save()
            return redirect('reviews:review_detail', review.pk)
        
        else :
            messages.warning(request, "댓글은 빈칸으로 제출하실 수 없습니다.")
            return redirect('reviews:review_detail', review.pk)


@login_required
def comment_like(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
        comment_is_liked = False
    else:

reviews/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>USINSA</title>
    <link href="{% static '/img/logo.png' %}" rel="shortcut icon" type="image/x-icon" style="font-size:32px;">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="relative">
  <header class="sticky top-0 z-50">{% include 'header.html' %}</header>
  <div id="wrap">
    {% block body %}  {% endblock body %}
  </div>
  
  <footer>{% include 'footer.html' %}</footer>

  
  {% block js%}
  <script src="{% static 'script.js' %}"></script>
  {% endblock js %}


  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
</body>
</html>

reviews/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>유신사</title>
</head>
<body>
  <footer class="bg-gray-200 py-5">
    <div class="text-center">
      <div class="text-gray-500"> 2조. 이조판서</div>
      <div class="flex justify-center my-4">
        <a href="https://github.com/fantael95" class="flex flex-col items-center mx-3 text-gray-500 hover:text-gray-900">
          <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"></svg>
          <span class="text-sm">이태영</span>
        </a>
        <a href="https://github.com/YongJuDo" class="flex flex-col items-center mx-3 text-gray-500 hover:text-gray-900">
          <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"></svg>
          <span class="text-sm">도용주</span>
        </a>
        <a href="https://github.com/Rilee-0320" class="flex flex-col items-center mx-3 text-gray-500 hover:text-gray-900">
          <svg class="w-7 h-7" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"></svg>
          <span class="text-sm">김규리</span>
        </a>
      </div>
    </div>
  </footer>
</body>
</html>

reviews/templates/header.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>USINSA</title>
</head>
<body>
  <nav class="bg-black">
    <div class="flex items-center p-3">
      <div class="mx-4">
        <a href="{% url 'reviews:index' %}" class="flex items-center">
          <span class="self-center text-2xl font-bold text-white">USINSA</span>
        </a>
      </div>
      <div class="grow text-center">
        <form method="GET" action="{% url 'reviews:search' %}">
          <input type="text" id="search-navbar" class="w-5/6 p-2 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-slate-300 focus:border-slate-300" placeholder="🔍 상품명을 검색하세요." name="query" value="{{ query }}">
        </form>
      </div>
      {% if request.user.is_authenticated %}
        <div class="mx-4 text-white">
          <a href="{% url 'accounts:profile' username=request.user.username %}">마이페이지</a>
        </div>
        <div class="mx-4 text-white">
          <a href="{% url 'accounts:basic_logout' %}">로그아웃</a>
        </div>
      {% else %}
        <div class="mx-4 text-white">
          <a href="{% url 'accounts:basic_login' %}">로그인</a>
        </div>
        <div class="mx-4 text-white">
          <a href="{% url 'accounts:basic_signup' %}">회원가입</a>
        </div>
      {% endif %}
    </div>
  </nav>
</body>
</html>